class OpCode:

    OP_RETURN = 0
    OP_CONSTANT = OP_RETURN + 1
    OP_NEGATE = OP_CONSTANT + 1
    OP_ADD = OP_NEGATE + 1
    OP_SUBTRACT = OP_ADD + 1
    OP_MULTIPLY = OP_SUBTRACT + 1
    OP_DIVIDE = OP_MULTIPLY + 1
